'use client';
import { useState } from 'react';
import { Activity, ArrowUpRight, BrainCircuit, CircleHelp, Clock3, FileText, FlaskConical, Play, Radar, Sparkles, Users, Waves } from 'lucide-react';

type Report={title:string;summary:string;scenarios:{name:string;likelihood:string;detail:string}[];signals:string[];caveat:string;validation?:{passed:boolean;warnings:string[];financial_checks:{price_increase_percent:number;churn_percent:number;estimated_revenue_change_percent:number;assumption:string;warning?:string}[];structural:{expected_agents:number;returned_agents:number;activity_records:number;scenario_paths:number;signals:number;graph_nodes:number;graph_edges:number;invalid_graph_edges:number};note:string};agent_profiles?:{username?:string;name:string;role:string;persona:string;opening_opinion:string;stance:string}[];activity?:{agent:string;action:string;content:string;round?:unknown}[];simulation?:{engine:string;platform:string;agents_requested:number;rounds_requested:number;recorded_activity_count:number;model:string};knowledge_graph?:{nodes:{id:string;label:string;type:string;description:string}[];edges:{source:string;target:string;relation:string}[];storage:string;graph_rag_enabled:boolean}};
const examples=['How might customers react to a 15% price increase?','What if a competitor launches a free tier?','How could public opinion evolve after a policy change?'];
export default function Home(){
 const [scenario,setScenario]=useState('How might customers react if we increase our subscription price by 15%?');
 const [context,setContext]=useState('A small SaaS business with a loyal customer base, a free trial, and three pricing tiers.');
 const [agents,setAgents]=useState('5'); const [rounds,setRounds]=useState('2');
 const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [report,setReport]=useState<Report|null>(null); const [jobId,setJobId]=useState('');
 async function run(){setLoading(true);setError('');setReport(null);setJobId('');try{const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,'');const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!supabaseUrl||!supabaseKey)throw new Error('Supabase is not configured. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel, then redeploy.');const endpoint=`${supabaseUrl}/functions/v1/scenariolab-simulate`;const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','apikey':supabaseKey,'Authorization':`Bearer ${supabaseKey}`},body:JSON.stringify({scenario,context,agents:Number(agents),rounds:Number(rounds)})});const raw=await res.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{data={}}if(!res.ok)throw new Error(data.error||data.detail||`Supabase simulation returned HTTP ${res.status}.`);if(!data.report)throw new Error('The simulation function returned an unexpected response. Check Supabase Edge Function logs.');setReport(data.report);setJobId(typeof data.job_id==='string'?data.job_id:'')}catch(e){setError(e instanceof TypeError?'Could not reach the Supabase simulation function. Check the Vercel Supabase URL/key and Edge Function deployment.':e instanceof Error?e.message:'Unexpected error. Try again.')}finally{setLoading(false)}}
 return <main className="min-h-screen">
  <header className="flex items-center justify-between px-5 md:px-10 py-5 border-b border-white/10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-[#8df0c6] text-[#07130f] flex items-center justify-center"><Waves/></div><div><div className="font-bold text-lg">Scenario<span className="text-[#8df0c6]">Lab</span></div><div className="text-[10px] muted tracking-[.17em] uppercase">Multi-perspective intelligence</div></div></div><nav className="hidden md:flex gap-6 text-sm muted"><a href="#workspace">Workspace</a><a href="#how">How it works</a><a href="#trust">Trust & limits</a></nav><a className="secondary text-sm flex items-center gap-2" href="#workspace">Open workspace <ArrowUpRight size={15}/></a></header>
  <section className="px-5 md:px-10 pt-14 pb-12 max-w-[1400px] mx-auto grid lg:grid-cols-[1.1fr_.9fr] gap-10 items-center"><div><div className="eyebrow flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-[#8df0c6]"/> Decision rehearsal, not guesswork</div><h1 className="text-5xl md:text-7xl font-semibold tracking-[-.065em] leading-[1.02] mt-5">Explore the <span className="text-[#8df0c6]">what if</span> before it happens.</h1><p className="text-lg muted leading-relaxed mt-6 max-w-2xl">Pressure-test a decision through distinct AI perspectives. Explore plausible outcomes, emerging risks, and signals worth watching before you commit.</p><a href="#workspace" className="primary inline-flex items-center gap-2 mt-8"><FlaskConical size={17}/> Build a simulation <ArrowUpRight size={16}/></a><div className="grid grid-cols-3 gap-4 max-w-xl mt-12"><div><div className="metric">01</div><div className="muted text-sm mt-1">Frame a scenario</div></div><div><div className="metric">02</div><div className="muted text-sm mt-1">Compare perspectives</div></div><div><div className="metric">03</div><div className="muted text-sm mt-1">Review possible paths</div></div></div></div>
  <div className="panel grid-bg p-5 md:p-7"><div className="eyebrow">Illustrative simulation map</div><h2 className="text-2xl font-semibold mt-2">One decision. Many paths.</h2><div className="h-64 flex items-center justify-center"><svg viewBox="0 0 440 260" className="w-full h-full" fill="none"><g stroke="#51627a" strokeOpacity=".7"><path d="M220 130 90 55M220 130 350 55M220 130 65 185M220 130 375 185M220 130 220 235M90 55 45 125M350 55 395 120M65 185 145 230M375 185 300 230"/></g>{[[90,55],[350,55],[65,185],[375,185],[220,235],[45,125],[395,120],[145,230],[300,230]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="5" fill={i%3===0?'#a99bff':'#8df0c6'}/>)}<circle cx="220" cy="130" r="46" fill="#8df0c6" fillOpacity=".08" stroke="#8df0c6" strokeOpacity=".6"/><circle cx="220" cy="130" r="22" fill="#8df0c6" fillOpacity=".2"/><circle cx="220" cy="130" r="5" fill="#8df0c6"/></svg></div><div className="grid grid-cols-3 gap-2"><div className="bg-white/[.035] rounded-xl p-3"><Users size={17} className="text-[#8df0c6]"/><div className="text-sm mt-2">Distinct voices</div></div><div className="bg-white/[.035] rounded-xl p-3"><Radar size={17} className="text-[#a99bff]"/><div className="text-sm mt-2">Possible paths</div></div><div className="bg-white/[.035] rounded-xl p-3"><Activity size={17} className="text-[#8df0c6]"/><div className="text-sm mt-2">Early signals</div></div></div></div></section>
  <section id="workspace" className="px-5 md:px-10 py-10 max-w-[1400px] mx-auto"><div className="mb-6"><div className="eyebrow">Your workspace</div><h2 className="text-3xl md:text-4xl font-semibold mt-2">Start with a question.</h2><p className="muted mt-2">Describe a decision and the context needed to explore it.</p></div><div className="grid lg:grid-cols-[.9fr_1.1fr] gap-5"><div className="panel p-5 md:p-7"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl bg-[#8df0c6]/10 text-[#8df0c6] flex items-center justify-center"><BrainCircuit/></div><div><h3 className="font-semibold">Simulation setup</h3><p className="muted text-sm">Define the situation to explore</p></div></div><label className="text-sm block mb-2" htmlFor="scenario">What do you want to explore?</label><textarea id="scenario" className="field min-h-28 resize-y" value={scenario} onChange={e=>setScenario(e.target.value)} maxLength={1200}/><div className="text-xs muted mt-2">{scenario.length}/1200 characters</div><div className="flex flex-wrap gap-2 mt-3">{examples.map(x=><button key={x} className="text-xs border border-white/10 rounded-full px-3 py-2 muted hover:text-white" onClick={()=>setScenario(x)}>{x}</button>)}</div><label className="text-sm block mt-6 mb-2" htmlFor="context">Background and assumptions</label><textarea id="context" className="field min-h-24 resize-y" value={context} onChange={e=>setContext(e.target.value)} maxLength={5000}/><div className="grid sm:grid-cols-2 gap-4 mt-5"><div><label className="text-sm block mb-2" htmlFor="agents">Agent perspectives</label><select id="agents" className="field" value={agents} onChange={e=>setAgents(e.target.value)}><option value="3">3 perspectives</option><option value="5">5 perspectives</option></select></div><div><label className="text-sm block mb-2" htmlFor="rounds">Reasoning rounds</label><select id="rounds" className="field" value={rounds} onChange={e=>setRounds(e.target.value)}><option value="1">1 round · lower cost</option><option value="2">2 rounds · balanced</option></select></div></div><button disabled={loading||scenario.trim().length<12} onClick={run} className="primary w-full mt-6 flex items-center justify-center gap-2 disabled:opacity-50">{loading?<><span className="animate-spin w-4 h-4 rounded-full border-2 border-black/30 border-t-black"/> Running simulation…</>:<><Play size={16}/> Run scenario simulation</>}</button>{error&&<div role="alert" className="mt-4 p-3 rounded-lg border border-rose-400/30 text-sm text-rose-200">{error}</div>}<p className="text-xs muted mt-3 flex items-start gap-2"><CircleHelp size={14} className="shrink-0 mt-0.5"/> Live runs require an LLM provider key. Usage may incur charges.</p></div>
  <div className="panel p-5 md:p-7 min-h-[480px]"><div className="eyebrow">Simulation output</div><h3 className="text-xl font-semibold mt-2">{report?report.title:'Your findings will appear here'}</h3>{report?<div className="mt-5 space-y-6">
  <section className="rounded-2xl border border-[#8df0c6]/20 bg-[#8df0c6]/[.04] p-4 md:p-5">
   <div className="flex items-center justify-between gap-3"><span className="eyebrow">Simulation brief</span><span className="text-xs muted">{report.simulation?.agents_requested||report.agent_profiles?.length||0} agents · {report.simulation?.rounds_requested||1} round(s)</span></div>
   <h4 className="text-2xl font-semibold leading-tight mt-2">{report.title}</h4><p className="text-sm leading-6 muted mt-3">{report.summary}</p>
   {jobId&&<p className="text-xs muted mt-3">Saved to Supabase · {jobId}</p>}
  </section>
  {report.agent_profiles&&report.agent_profiles.length>0&&<section>
   <div className="flex items-end justify-between gap-3"><div><div className="eyebrow">Meet the stakeholders</div><h4 className="text-xl font-semibold mt-1">Agent profiles</h4></div><span className="text-xs muted">{report.agent_profiles.length} perspectives</span></div>
   <div className="space-y-3 mt-4">{report.agent_profiles.map((agent,i)=><article key={agent.username||agent.name||i} className="rounded-2xl border border-white/10 p-4 md:p-5">
    <div className="flex items-start gap-4"><div className={`w-14 h-14 md:w-16 md:h-16 shrink-0 rounded-2xl flex items-center justify-center text-lg font-semibold border border-white/10 ${['bg-[#8df0c6]/15 text-[#8df0c6]','bg-[#a99bff]/15 text-[#c5baff]','bg-amber-300/10 text-amber-200'][i%3]}`}>{(agent.name||agent.username||`A`).split(/[ _-]/).map(part=>part[0]).join('').slice(0,2).toUpperCase()}</div>
     <div className="min-w-0 flex-1"><div className="text-xs muted uppercase tracking-wider">Agent {i+1} · {agent.stance}</div><h5 className="text-lg font-semibold mt-1">{agent.name||agent.username||`Agent ${i+1}`}</h5><p className="text-sm text-[#8df0c6] mt-1">{agent.role}</p><p className="text-sm muted mt-2">{agent.persona}</p><div className="mt-3"><div className="text-xs muted mb-1">Initial opinion</div><p className="text-base leading-7">“{agent.opening_opinion}”</p></div></div>
    </div>
   </article>)}</div>
  </section>}
  {report.activity&&report.activity.length>0&&<section><div className="eyebrow">The conversation</div><h4 className="text-xl font-semibold mt-1">What each agent said</h4><div className="mt-4 space-y-3">{report.activity.map((event,i)=>{const agent=report.agent_profiles?.find(p=>p.username===event.agent||p.name===event.agent);const idx=Math.max(0,report.agent_profiles?.findIndex(p=>p.username===event.agent||p.name===event.agent)??0);return <article key={i} className="flex gap-3 md:gap-4"><div className={`w-10 h-10 shrink-0 rounded-xl flex items-center justify-center text-xs font-semibold ${['bg-[#8df0c6]/15 text-[#8df0c6]','bg-[#a99bff]/15 text-[#c5baff]','bg-amber-300/10 text-amber-200'][idx%3]}`}>{(agent?.name||event.agent).split(/[ _-]/).map(part=>part[0]).join('').slice(0,2).toUpperCase()}</div><div className="flex-1 rounded-2xl border border-white/10 p-4"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-sm">{agent?.name||event.agent}</span>{agent?.role&&<span className="text-xs muted">· {agent.role}</span>}<span className="text-xs rounded-full bg-white/[.06] px-2 py-1 muted">{event.action}</span>{typeof event.round==='number'&&<span className="text-xs muted">Round {event.round}</span>}</div><p className="text-sm leading-7 mt-2">{event.content}</p></div></article>})}</div></section>}
  {report.validation?.financial_checks&&report.validation.financial_checks.length>0&&<section><div className="eyebrow">Numbers at a glance</div><h4 className="text-xl font-semibold mt-1">Estimated financial impact</h4><div className="grid sm:grid-cols-2 gap-3 mt-4">{report.validation.financial_checks.map((check,i)=><article key={i} className="rounded-2xl border border-white/10 p-4"><p className="text-xs muted">{check.price_increase_percent}% price increase · {check.churn_percent}% churn</p><div className={`text-3xl font-semibold mt-2 ${check.estimated_revenue_change_percent>=0?'text-[#8df0c6]':'text-amber-200'}`}>{check.estimated_revenue_change_percent>=0?'+':''}{check.estimated_revenue_change_percent}%</div><p className="text-sm mt-1">estimated revenue change</p><p className="text-xs muted leading-5 mt-3">{check.assumption}</p>{check.warning&&<p className="text-xs text-amber-200 mt-2">{check.warning}</p>}</article>)}</div></section>}
  {report.scenarios?.length>0&&<section><div className="eyebrow">Possible futures</div><h4 className="text-xl font-semibold mt-1">Scenario paths</h4><div className="grid sm:grid-cols-2 gap-3 mt-4">{report.scenarios.map((item,i)=><article key={item.name} className="rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs muted">PATH {String(i+1).padStart(2,'0')}</span><span className="text-xs rounded-full bg-[#a99bff]/10 text-[#c5baff] px-2 py-1">{item.likelihood}</span></div><h5 className="font-semibold mt-3">{item.name}</h5><p className="text-sm leading-6 muted mt-2">{item.detail}</p></article>)}</div></section>}
  {report.signals?.length>0&&<section><div className="eyebrow">What to watch</div><h4 className="text-xl font-semibold mt-1">Early warning signals</h4><div className="grid sm:grid-cols-2 gap-2 mt-4">{report.signals.map((signal,i)=><div key={signal} className="flex gap-3 items-start rounded-xl bg-white/[.035] p-3"><span className="w-6 h-6 rounded-lg bg-[#8df0c6]/10 text-[#8df0c6] text-xs flex items-center justify-center shrink-0">{i+1}</span><p className="text-sm leading-6">{signal}</p></div>)}</div></section>}
  {report.knowledge_graph&&<details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-semibold text-sm">Explore the knowledge map <span className="muted font-normal">· {report.knowledge_graph.nodes.length} concepts, {report.knowledge_graph.edges.length} links</span></summary><div className="flex flex-wrap gap-2 mt-4">{report.knowledge_graph.nodes.map(node=><span key={node.id} title={node.description} className="rounded-full border border-[#a99bff]/30 bg-[#a99bff]/[.06] px-3 py-2 text-xs">{node.label}<span className="muted ml-2">{node.type}</span></span>)}</div><div className="space-y-2 mt-4">{report.knowledge_graph.edges.slice(0,12).map((edge,i)=><p key={i} className="text-xs muted">{report.knowledge_graph?.nodes.find(n=>n.id===edge.source)?.label||edge.source} <span className="text-[#8df0c6]">— {edge.relation} →</span> {report.knowledge_graph?.nodes.find(n=>n.id===edge.target)?.label||edge.target}</p>)}</div></details>}
  {report.validation&&<details className="rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-semibold text-sm">Quality checks <span className={report.validation.passed?"text-[#8df0c6]":"text-amber-200"}>· {report.validation.passed?"Passed":"Review needed"}</span></summary><div className="grid grid-cols-3 gap-2 mt-4">{[[ "Agents",report.validation.structural.returned_agents],["Activity",report.validation.structural.activity_records],["Paths",report.validation.structural.scenario_paths],["Signals",report.validation.structural.signals],["Graph nodes",report.validation.structural.graph_nodes],["Graph links",report.validation.structural.graph_edges]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-white/[.035] p-3"><div className="text-xs muted">{label}</div><div className="font-semibold mt-1">{value}</div></div>)}</div>{report.validation.warnings.map((warning,i)=><p key={i} className="text-xs text-amber-200 mt-2">{warning}</p>)}<p className="text-xs muted mt-3">{report.validation.note}</p></details>}
  <section className="rounded-xl border border-amber-300/20 bg-amber-300/[.04] p-4"><div className="text-sm font-semibold text-amber-100">Keep in mind</div><p className="text-sm leading-6 muted mt-2">{report.caveat}</p><p className="text-xs muted mt-2">AI-generated scenarios are illustrative, not verified facts or calibrated forecasts.</p></section>
  <button className="secondary flex items-center gap-2 text-sm" onClick={()=>navigator.clipboard?.writeText(JSON.stringify(report,null,2))}><FileText size={15}/> Copy report data</button>
 </div>:<div className="h-80 flex flex-col items-center justify-center text-center"><div className="w-16 h-16 rounded-2xl bg-white/[.04] flex items-center justify-center"><Sparkles size={28} className="text-[#8df0c6]"/></div><h4 className="text-lg font-semibold mt-5">A clear, visual report</h4><p className="muted text-sm leading-6 mt-2 max-w-sm">Meet the agents, follow their conversation, and scan possible outcomes without digging through a wall of text.</p><div className="flex gap-4 mt-5 text-sm muted"><span className="flex items-center gap-2"><Activity size={15}/> Signals</span><span className="flex items-center gap-2"><Clock3 size={15}/> Uncertainty</span></div>div className="w-16 h-16 rounded-2xl bg-white/[.04] flex items-center justify-center"><Sparkles size={28} className="text-[#8df0c6]"/></div><h4 className="text-lg font-semibold mt-5">A structured report, not a magic answer</h4><p className="muted text-sm leading-6 mt-2 max-w-sm">Compare plausible paths, make assumptions visible, and surface early-warning signals.</p><div className="flex gap-4 mt-5 text-sm muted"><span className="flex items-center gap-2"><Activity size={15}/> Signals</span><span className="flex items-center gap-2"><Clock3 size={15}/> Uncertainty</span></div></div>}</div></div></section>
  <section id="how" className="px-5 md:px-10 py-12 border-t border-white/10"><div className="max-w-[1400px] mx-auto"><div className="eyebrow">Designed for decisions</div><h2 className="text-3xl font-semibold mt-3">A clear path from question to insight.</h2><div className="grid md:grid-cols-3 gap-4 mt-7">{[['01 / Context','Frame the situation','Start with a decision and make assumptions explicit.'],['02 / Perspectives','Challenge the obvious','Explore stakeholder viewpoints and conflicting incentives.'],['03 / Findings','Plan for possibilities','Review risks and signals that could change your decision.']].map(x=><div key={x[0]} className="panel p-6"><div className="text-[#8df0c6] text-sm">{x[0]}</div><h3 className="text-xl font-semibold mt-4">{x[1]}</h3><p className="muted leading-6 mt-2 text-sm">{x[2]}</p></div>)}</div></div></section>
  <section id="trust" className="px-5 md:px-10 py-8"><div className="max-w-[1400px] mx-auto panel p-6"><h3 className="font-semibold">Decision support—not guaranteed forecasts.</h3><p className="muted text-sm leading-6 mt-2">AI outputs can be wrong or biased and depend on assumptions and model choice. Likelihood labels are qualitative, not calibrated probabilities. This lightweight LLM simulation does not run CAMEL-OASIS or reproduce MiroFish's full graph memory. Agent activity is synthetic model output, not observed real-world behavior.</p></div></section><footer className="px-5 md:px-10 py-8 border-t border-white/10 flex justify-between text-xs muted"><span>© 2026 ScenarioLab</span><span>Independent prototype · Not affiliated with MiroFish</span></footer>
 </main>;
}
